version: 2.1

orbs: 
  npm-publisher: uraway/npm-publisher@0.2.0

workflows:
  build_publish:
    jobs:
      - npm-publisher/publish-from-package-version:
          name: Publish NPM Package
          filters:
            branches:
              only:
                - main
          post-publish-steps:
            - save_cache:
                key: v1-node-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
                paths:
                  - node_modules
          pre-publish-steps:
            - restore_cache:
                keys:
                  - v1-node-cache-{{ .Branch }}-{{ checksum "package-lock.json"}}
                  - v1-node-cache-
            - run: npm install
            - run: npm run build
          publish-token-variable: NPM_TOKEN
          push-git-tag: false
