version: 2.1

orbs:
  node: circleci/node@1.1
  npm-publisher: uraway/npm-publisher@0.2.0

jobs:
  lint:
    executor:
      name: node/default
      tag: "16"
    steps:
      - checkout
      - run: npm install
      - run: npm run lint

workflows:
  build_publish:
    jobs:
      - lint:
          name: Lint
      - npm-publisher/publish-from-package-version:
          name: Publish NPM Package
          requires:
            - Lint
          filters:
            branches:
              only:
                - main
          post-publish-steps:
            - save_cache:
                key: v1-node-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
                paths:
                  - node_modules
          pre-publish-steps:
            - restore_cache:
                keys:
                  - v1-node-cache-{{ .Branch }}-{{ checksum "package-lock.json"}}
                  - v1-node-cache-
            - run: npm install
          publish-token-variable: NPM_TOKEN
          push-git-tag: false
